Collection export
ilovevinylrecs/andynystrom pull request #10
Opened 2021-04-13 17:47 UTC by ilovevinylrecs

Adds collection-export.js file to project

2021-04-13 17:53 UTC, desmondmorris commented on collection-export/collection-export.js
> +const asyncDiscogsCall = async () =>  {
This function should be renamed more appropriately.  Some thing like `fetchCollection`

2021-04-13 17:53 UTC, desmondmorris commented on collection-export/collection-export.js
> +    const vinyls = await new Discogs('ilovevinylrecs/1.0', {userToken: process.env.DISCOGS_USER_TOKEN}).user().collection();
The variable name `vinyls` does not make much sense here.  What is a better name for this variable?

2021-04-13 17:54 UTC, desmondmorris commented on collection-export/collection-export.js
> +        break;
Is this `break` necssary?

2021-04-13 17:54 UTC, desmondmorris commented on collection-export/collection-export.js
> +    const vinyls = await new Discogs('ilovevinylrecs/1.0', {userToken: process.env.DISCOGS_USER_TOKEN}).user().collection();
`ilovevinylrecs` should be in a variable as you are referencing it a few times.

2021-04-13 17:55 UTC, desmondmorris commented on collection-export/collection-export.js
> +    const Discogs = require('disconnect').Client;({
Please move the require statement to the top of the file.

2021-04-13 17:56 UTC, desmondmorris commented on collection-export/collection-export.js
> +        const releases = await vinyls.getReleases('ilovevinylrecs', 0, {page: page, per_page: 500, sort: 'artist', sort_order: 'asc'});
This variable is an API result in which the releases are a property.  I would name this variable `result` or `data` something less specific than it is now

2021-04-13 17:56 UTC, desmondmorris commented on pages/api/vinyls.tsx
> +
I dont think this change is meant for this pr right?

2021-04-13 17:57 UTC, desmondmorris requested changes
I left some comments.  This file should be written in typescript.  You will need to rename the extension then update accordingly.

2021-04-13 17:59 UTC, ilovevinylrecs commented on collection-export/collection-export.js
> +const asyncDiscogsCall = async () =>  {
changed this to fetchCollection

2021-04-13 18:03 UTC, ilovevinylrecs commented on collection-export/collection-export.js
> +    const vinyls = await new Discogs('ilovevinylrecs/1.0', {userToken: process.env.DISCOGS_USER_TOKEN}).user().collection();
changed this variable name to collectionDataBase

2021-04-13 18:04 UTC, ilovevinylrecs commented on collection-export/collection-export.js
> +        break;
No, bc once page === releases.pagination.pages then done = true, and it will break out of the while loop. Removed.

2021-04-13 18:07 UTC, ilovevinylrecs commented on collection-export/collection-export.js
> +    const vinyls = await new Discogs('ilovevinylrecs/1.0', {userToken: process.env.DISCOGS_USER_TOKEN}).user().collection();
assigned this to the variable userName

2021-04-13 18:35 UTC, ilovevinylrecs commented on pages/api/vinyls.tsx
> +
Yeah sorry about that, I removed the extra space in that file, got included when I added all changes to commit.

2021-04-13 21:21 UTC, ilovevinylrecs commented on collection-export/collection-export.js
> +        const releases = await vinyls.getReleases('ilovevinylrecs', 0, {page: page, per_page: 500, sort: 'artist', sort_order: 'asc'});
renamed to data

2021-04-16 14:19 UTC, desmondmorris commented on collection-export/collection-export.ts
> +export const fetchCollection = async () =>  {
This function isnt returning anything.  We should add a return type expressing this.  Since this is an async function, it reurns a Promise.  The Promise in our case does not return anything.  So, we would us a type like this: `Promise<void>`

`export const fetchCollection = async (): Promise<void> => {`

2021-04-16 14:20 UTC, desmondmorris commented on collection-export/collection-export.ts
> +        const versionDisconnect = "/1.2.2";
this variable name is misleading.  this is just the API version right?

2021-04-16 14:20 UTC, desmondmorris commented on collection-export/collection-export.ts
> +        const versionDisconnect = "/1.2.2";
Its a good practice to put all constants at the top of the file.  Not to be confused with variables in which we use the keyword `constant`.  Like literal constant values, like these two items

2021-04-16 14:22 UTC, desmondmorris commented on collection-export/collection-export.ts
> +        const userAgentVersionDisconnect = userAgent.concat(versionDisconnect);
I would use a template sting here `${DISCOGS_USERNAME}/${DISCOGS_API_VERSION}`

2021-04-16 14:23 UTC, desmondmorris commented on collection-export/collection-export.ts
> +        const collectionDataBase = await new Discogs(userAgentVersionDisconnect, {userToken: process.env.DISCOGS_USER_TOKEN}).user().collection();
Do we need await here?  Does this return a promise?

2021-04-16 14:24 UTC, desmondmorris commented on pages/api/vinyls.tsx
You may need to do a bit more git-fu to remove this file from this set of changes.  Now we have a commit where you have removed the white space then a new commit where you added it back.

2021-04-16 14:25 UTC, desmondmorris commented on tsconfig.json
> +, "pages/api/messages/[id].js"],
Why is this added here?

2021-04-16 18:37 UTC, ilovevinylrecs commented on collection-export/collection-export.ts
> +        const versionDisconnect = "/1.2.2";
Yeah just returns API call, renamed to fetchCollectionAPI

2021-04-16 18:38 UTC, ilovevinylrecs commented on collection-export/collection-export.ts
> +        const versionDisconnect = "/1.2.2";
ok cool, moved these outside the function, but below the require statement

2021-04-17 01:40 UTC, ilovevinylrecs commented on collection-export/collection-export.ts
> +        const collectionDataBase = await new Discogs(userAgentVersionDisconnect, {userToken: process.env.DISCOGS_USER_TOKEN}).user().collection();
No promise returned here, removed await.

2021-04-17 01:45 UTC, ilovevinylrecs commented on tsconfig.json
> +, "pages/api/messages/[id].js"],
I was attempting to fix the TS error I was receiving and tried adding something this fix, but it wasn't correct.

2021-04-17 02:19 UTC, ilovevinylrecs commented on collection-export/collection-export.ts
> +export const fetchCollection = async () =>  {
When I add this type, I can no longer run this script - is that expected behavior? I don't receive any errors from VS.

2021-04-20 02:58 UTC, ilovevinylrecs commented on pages/api/vinyls.tsx
Moving forward if I mess with one of these other files and essentially don't make any meaningful changes, instead of using git add ., I should just git add <filename> the files I want to include, and use git checkout --<filename> for the changes that shouldn't be tracked to keep them out of the commit, is that correct?

2021-04-27 10:15 UTC, desmondmorris commented on collection-export/collection-export.ts
> +    converter.json2csv(collection, (err, csv) => {
As I mentioned, we will not be able to go this route, as you should just insert the items immediately after you get them from the API.

1.   Take the array of items in collections and build the insert statement as a string of SQL.
2.   Issue the query using the pg module

2021-04-29 05:12 UTC, ilovevinylrecs commented on collection-export/collection-export.ts
> +    converter.json2csv(collection, (err, csv) => {
addresses this in collection-export-postgres.ts file

2021-05-04 13:54 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +            pool.end();
Move this outside of the loop.

2021-05-04 13:55 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +//comment out export and promise<void> in order to get script to run
Why do you need to do this?  Are you running it via node or ts-node?

2021-05-04 13:56 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +        pool.query(query, (err, res) => {
This should be async right?

2021-05-04 13:59 UTC, desmondmorris requested changes
Some notes/questions in the review.  Did you want me to review the practice scripts?  These dont need to be in this repo i think

2021-05-04 14:57 UTC, ilovevinylrecs commented on collection-export/collection-export-postgres.ts
> +//comment out export and promise<void> in order to get script to run
If I don't comment out this export, then this script won't run via node. But if I push this without the export, then the whole site deploy fails bc of TS error - haven't found a way to resolve this yet.

2021-05-04 15:02 UTC, ilovevinylrecs commented on collection-export/collection-export-postgres.ts
> +        pool.query(query, (err, res) => {
Added await here

2021-05-06 11:13 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +//comment out export and promise<void> in order to get script to run
node cannot run typescript.  You need to use ts-node

2021-05-06 11:17 UTC, desmondmorris requested changes

2021-05-06 11:17 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +
This is looking pretty good.  It would be more efficient if you created a sql string with all of the rows.  This way you would only need to issue a single sql query.

2021-05-06 11:17 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +    const pool = new Pool({
I dont think you meed the empty object here

2021-05-07 02:48 UTC, ilovevinylrecs commented on collection-export/collection-export-postgres.ts
> +//comment out export and promise<void> in order to get script to run
i have ts-node installed, but I keep getting this error:
andynystrom@Andy-Nystrom collection-export % ts-node collection-export-postgres.ts
zsh: command not found: ts-node
which is confusing because this script run when I use:
andynystrom@Andy-Nystrom collection-export % node collection-export-postgres.ts

2021-05-07 03:07 UTC, ilovevinylrecs commented on collection-export/collection-export-postgres.ts
> +
I'm confused that what I have now isn't a single query with all the rows for table - should I get rid of assigning the string to the variable query?

2021-05-07 13:54 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +//comment out export and promise<void> in order to get script to run
ts-node is not installed globally.  This is why I suggested using npx - `npx ts-node filename`

2021-05-07 13:58 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +
You are running a query per row currently.  Every time you loop, it runs a insert.

This statement for example, inserts 

You are currently doing the equivalent to this:
`INSERT INTO TABLE mytable (a,b, c) VALUES (1,2,3)`
`INSERT INTO TABLE mytable (a,b, c) VALUES (4,5,6)`
`INSERT INTO TABLE mytable (a,b, c) VALUES (7,8,9)`

We should be doing this:
`INSERT INTO TABLE mytable (a,b, c) VALUES (1,2,3), (4,5,6), (7,8,9)`
A single statement inserting many rows

2021-05-09 05:08 UTC, ilovevinylrecs commented on collection-export/collection-export-postgres.ts
> +
pushed update to resolve this

2021-05-09 05:09 UTC, ilovevinylrecs commented on collection-export/collection-export-postgres.ts
> +//comment out export and promise<void> in order to get script to run
added code to tsconfig and script is working correctly using npx ts-node filename

2021-05-10 12:37 UTC, desmondmorris requested changes
OK, so we are getting closer:

1.  You need to remove all data before you run an insert
2.   Now we have two loops.  Can we create the SQL statement string from the while loop instead?

2021-05-13 18:35 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +    let output = collection.map(item => `('${item.id}', '${item.instance_id}',
Does this work currently?  Dont you need a command in between each set of values?

2021-05-13 18:35 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +        collection = collection.concat(data.releases);
What if you did the map on data.releases and added that to the output variable?

2021-05-13 21:19 UTC, ilovevinylrecs commented on collection-export/collection-export-postgres.ts
> +    let output = collection.map(item => `('${item.id}', '${item.instance_id}',
I just tested and ran this again and it's working correctly, am I just getting lucky and missing something?

2021-05-15 00:36 UTC, ilovevinylrecs commented on collection-export/collection-export-postgres.ts
> +    let output = collection.map(item => `('${item.id}', '${item.instance_id}',
we are good here

2021-05-20 13:55 UTC, desmondmorris commented on collection-export/collection-export-postgres.ts
> +
Nice work.

2021-05-20 13:55 UTC, desmondmorris approved these changes

2021-05-20 14:10 UTC, merged