Typescript
ilovevinylrecs/andynystrom pull request #8
Opened 2021-04-05 13:35 UTC by ilovevinylrecs

2021-04-05 13:42 UTC, desmondmorris commented on pages/flatfile/index.tsx
>      console.log(posters)
Remove this concole log. We typically do not want log statements that are being used for debugging  to land in production

2021-04-05 13:47 UTC, desmondmorris requested changes

2021-04-05 13:47 UTC, desmondmorris commented on pages/messages/[id].tsx
>              const data = await fetch('/api/messages')
You should create a new api endpoint that takes the id as a parameter.  Then instead of get all of the entries, you can pull a single entry from contentful.

https://nextjs.org/docs/api-routes/dynamic-api-routes
https://contentful.github.io/contentful.js/contentful/8.2.1/ContentfulClientAPI.html#.getEntry

2021-04-05 13:51 UTC, ilovevinylrecs commented on pages/flatfile/index.tsx
>      console.log(posters)
Removed line 18 from this file

2021-04-05 13:53 UTC, ilovevinylrecs commented on pages/flatfile/index.tsx
>      console.log(posters)
Removed this console.log statement

2021-04-06 11:03 UTC, desmondmorris requested changes

2021-04-06 11:03 UTC, desmondmorris commented on pages/api/messages/[id].tsx
> +    // res.end(`Post: ${id}`)
You can remove this line now

2021-04-06 11:03 UTC, desmondmorris commented on pages/messages/index.tsx
> +            const data = await fetch('/api/messages/messages')
Is that url correct?

2021-04-06 13:13 UTC, ilovevinylrecs commented on pages/messages/index.tsx
> +            const data = await fetch('/api/messages/messages')
This URL was correct for the messages landing page, I changed the naming convention for this to follow Next documentation, landing page API renamed to index.tsx

2021-04-06 13:16 UTC, ilovevinylrecs commented on pages/api/messages/[id].tsx
> +    // res.end(`Post: ${id}`)
Removed this commented out code.

2021-04-06 13:58 UTC, ilovevinylrecs commented on pages/messages/[id].tsx
>              const data = await fetch('/api/messages')
Created new API endpoint that takes Id as parameter

2021-04-06 16:32 UTC, desmondmorris approved these changes

2021-04-06 18:49 UTC, merged